const images = {
  home: require('./images/home.png'),
  profile: require('./images/user.png'),
  logout: require('./images/logout.png'),
  prevlnk: require('./images/prev.png'),
  logo: require('./images/logo.png'),
  toggle: require('./images/toggle.png'),
  converter_search: require('./images/co-search.png'),
  view: require('./images/view.png'),
  cart: require('./images/cart.png'),
  converterimage1: require('./images/conv1.jpg'),
  converterimage2: require('./images/conv2.jpg'),
  converterimage3: require('./images/conv3.jpg'),
  calculator: require('./images/calculator.png'),
  header: require('./images/header.png'),
  shopping_basket: require('./images/shopping-cart.png'),
  edit: require('./images/edit_icon.png'),
  save: require('./images/floppySave.png'),
  delete: require('./images/delete.png'),
  refresh: require('./images/refresh.png'),
  download: require('./images/download.png'),
  email: require('./images/email.png'),
  settings: require('./images/settings.png'),
  contact: require('./images/contact.png'),
  user_icon: require('./images/02Username.png'),
  pswd_icon: require('./images/Password.png'),
  login_ar: require('./images/login-ar.png'),
  search: require('./images/Search.png'),
  filter: require('./images/filter.png'),
  addconverter: require('./images/add-convertor.png'),
  splash_topicon: require('./images/splash-top-icon.png'),
  logo_splash: require('./images/logo-splash.png'),
  splash_boticon: require('./images/splash-bottom-icon.png'),
  loader: require('./images/loader.gif'),
  up: require('./images/acc-up.png'),
  down: require('./images/acc-down.png'),
  upload: require('./images/upload.png'),
  whatsapp: require('./images/whatsapp.png'),
  chatLogo: require('./images/chat.png'),
};

export default images;
