import {StyleSheet} from 'react-native';
import R from '../../resources/R';

const Styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: R.colors.white,
    flexGrow: 1,
  },
  contentContainer: {
    flex: 1,
  },
  textContainer: {
    marginTop: 20,
    marginHorizontal: 20,
  },
  coloumncontainer: {
    flexDirection: 'row-reverse',
    paddingBottom: 10,
  },

  item: {
    flex: 0.5,
    width: '50%',
    padding: 0,
  },
  item1: {width: '35%'},
  item2: {width: '65%', alignItems: 'flex-start'},
  headingSubTittle: {
    fontSize: 18,
    color: R.colors.gold,
    fontFamily: 'SemplicitaPro-Bold',
    marginLeft: Platform.OS == 'ios' ? 50 : 0,
  },
  headingBalance: {
    fontSize: 14,
    color: R.colors.blue,
    fontFamily: 'SemplicitaPro-Bold',
    textAlign: 'left',
  },

  textStyle: {
    color: R.colors.white,
  },
  textStyleB: {
    color: R.colors.white,
    fontFamily: 'SemplicitaPro-Bold',
  },

  boxcontainer: {
    borderColor: R.colors.mediumgray,
    borderWidth: 2,
    borderRadius: 7,
    width: '100%',
    padding: 10,
    paddingLeft: 20,
    paddingRight: 20,
  },
  coloumncontainer1: {
    flexDirection: 'row-reverse',
    padding: 10,
    paddingLeft: 20,
    paddingRight: 20,
  },
  coloumncontainer3: {
    flexDirection: 'column',
    padding: 10,
    paddingLeft: 20,
    paddingRight: 20,
    marginBottom: 250,
  },
  formLbl: {
    color: R.colors.blue,
    fontFamily: 'SemplicitaPro-Regular',
    fontSize: 15,
    marginBottom: 5,
    textAlign: 'right',
  },
  formmb: {
    marginBottom: 10,
    fontFamily: 'SemplicitaPro-SemiBold',
  },
  // blubtn: {
  //   backgroundColor: R.colors.blue,
  //   borderRadius: 5,
  //   padding: 8,
  //   marginEnd: 10,
  //   marginTop: 5,
  //   marginBottom: 1,
  //   maxHeight: 50,
  // },
  blubtn: {
    backgroundColor: R.colors.blue,
    borderRadius: 5,
    marginBottom: 1,
    padding: 8,
  },
  modalView: {
    margin: 10,
    marginTop: 50,
    backgroundColor: 'white',
    borderRadius: 0,
    padding: 5,
    display: 'flex',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  button: {
    borderRadius: 5,
    padding: 10,
    width: 80,
    textAlign: 'center',
    alignItems: 'center',
  },
  buttonOpen: {
    backgroundColor: R.colors.blue,
  },
  buttonClose: {
    backgroundColor: R.colors.darkgray,
    padding: 10,
    color: R.colors.white,
    borderRadius: 5,
    fontSize: 14,
    marginTop: 10,
    paddingLeft: 5,
    paddingRight: 5,
    fontFamily: 'SemplicitaPro-Bold',
    marginRight: 20,
  },
  buttonClose1: {
    backgroundColor: R.colors.blue,
    fontFamily: 'SemplicitaPro-Bold',
  },

  modalText: {
    marginBottom: 15,
    textAlign: 'left',
  },
  headingModal: {
    fontSize: 15,
    color: R.colors.white,
    fontFamily: 'SemplicitaPro-Bold',
    paddingTop: 5,
  },
  modalbg: {
    backgroundColor: R.colors.blue,
    padding: 2,
    paddingEnd: 10,
    paddingTop: 5,
    paddingLeft: 10,
    marginBottom: 10,
    width: '103%',
    marginRight: -5,
    marginTop: -5,
  },
  headingBtn: {
    position: 'absolute',
    right: 10,
    top: 10,
  },
  formcontainer: {
    padding: 10,
  },
  mandatoryLbl: {
    fontSize: 13,
    color: R.colors.red,
    textAlign: 'left',
    marginBottom: 5,
    alignItems: 'flex-end',
  },
  mandatory: {
    color: R.colors.red,
    fontFamily: 'SemplicitaPro-Bold',
  },

  formmt: {
    marginTop: 12,
  },
  textInput: {
    color: R.colors.lightgray,
    fontSize: 12,
    height: 40,
    fontFamily: 'SemplicitaPro-Regular',
    borderRadius: 5,
    backgroundColor: '#F6F9FA',
    borderColor: R.colors.mediumgray,
    borderWidth: 1,
    paddingLeft: 10,
    paddingRight: 10,
    textAlign: 'right',
    justifyContent: 'center',
  },
  btnContainer: {
    display: 'flex',
    justifyContent: 'flex-end',
    flexDirection: 'row-reverse',
  },
  btnContainer1: {
    display: 'flex',
    justifyContent: 'flex-start',
    flexDirection: 'row-reverse',
    marginLeft: '50%',
    marginTop: 10,
  },

  modalBtn: {
    backgroundColor: R.colors.blue,
    padding: 10,
    color: R.colors.white,
    borderRadius: 5,
    fontSize: 14,
    marginTop: 10,
    paddingLeft: 25,
    paddingRight: 25,
    fontFamily: 'SemplicitaPro-Bold',
  },
  inputTexts: {
    borderColor: R.colors.mediumgray,
    borderWidth: 1,
    borderRadius: 5,
    backgroundColor: '#F6F9FA',
    height: 40,
    justifyContent: 'center',
  },
  headers: {
    backgroundColor: '#EAE6E6',
    padding: 10,
    width: '100%',
    elevation: 2,
    borderColor: R.colors.mediumgray,
    borderWidth: 1,
    fontFamily: 'SemplicitaPro-SemiBold',
    color: R.colors.black,
    fontSize: 16,
    justifyContent: 'space-between',
    flexDirection: 'row-reverse',
  },
  headersText: {
    fontFamily: 'SemplicitaPro-SemiBold',
    color: R.colors.black,
    fontSize: 16,
    lineHeight: 25,
    width: '100%',
    marginRight: 10,
    textAlign: 'right',
  },
  header: {
    width: '100%',
    fontFamily: 'SemplicitaPro-SemiBold',
    color: R.colors.black,
    fontSize: 16,
    textAlign: 'right',
  },
  headercon: {
    backgroundColor: '#EAE6E6',
    padding: 10,
    width: '100%',
    elevation: 2,
    borderColor: R.colors.mediumgray,
    borderWidth: 1,
    marginTop: 2,
    fontFamily: 'SemplicitaPro-SemiBold',
    color: R.colors.black,
    fontSize: 16,
    position: 'relative',
  },
  headerText: {
    textAlign: 'left',
    fontSize: 16,
    fontWeight: '500',
    fontFamily: 'SemplicitaPro-Bold',
    color: R.colors.black,
  },
  tableHead: {
    textAlign: 'left',
    fontSize: 16,
    fontWeight: '700',
    fontFamily: 'SemplicitaPro-Bold',
    color: R.colors.black,
  },
  tabletext: {
    padding: 7,
    fontFamily: 'SemplicitaPro-Regular',
    color: R.colors.black,
    flexDirection: 'row-reverse',
    textAlign: 'right',
    flex: 1,
  },

  content: {
    padding: 20,
    width: '100%',
    backgroundColor: '#F6F6F6',
    borderColor: R.colors.mediumgray,
    borderWidth: 1,
    flex: 1,
    flexDirection: 'row-reverse',
  },
  active: {
    backgroundColor: R.colors.blue,
  },
  inactive: {
    backgroundColor: R.colors.gray,
  },

  lotHeader: {
    backgroundColor: R.colors.blue,
    color: R.colors.white,
    padding: 10,
    textAlign: 'center',
    fontFamily: 'SemplicitaPro-Bold',
    fontSize: 16,
    borderTopLeftRadius: 7,
    borderTopRightRadius: 7,
    marginBottom: -1,
  },

  formcont: {
    display: 'flex',
    flexDirection: 'row-reverse',
    padding: 4,
    marginLeft: 10,
    marginRight: 10,
  },
  formLblr: {
    color: R.colors.blue,
    fontFamily: 'SemplicitaPro-Medium',
    fontSize: 16,
    marginBottom: 5,
    fontWeight: '600',
    width: '50%',
  },

  formLbll: {
    color: R.colors.black,
    fontFamily: 'SemplicitaPro-Medium',
    fontSize: 16,
    marginBottom: 5,
    fontWeight: '600',
    width: '50%',
    textAlign: 'right',
  },
  aligncenter: {
    textAlign: 'center',
  },
  bigfont: {
    fontFamily: 'SemplicitaPro-Bold',
    fontSize: 20,
    marginBottom: 5,
    fontWeight: 'bold',
    color: R.colors.black,
  },
  centeredView: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.2)',
  },
  loadercontainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    flexDirection: 'column',
  },
  mgrT15: {
    marginTop: 15,
  },
  blubtn2: {
    backgroundColor: R.colors.blue,
    borderRadius: 5,
    padding: 5,
    margin: 2,
    width: 35,
    height: 30,
    justifyContent: 'center',
    paddingLeft: 8,
  },
  prevlnk: {
    height: 17,
    width: 17,
    resizeMode: 'contain',
    transform: [{scaleX: -1}],
  },
  rowrev: {
    flexDirection: 'row-reverse',
  },
  alignleft: {
    textAlign: 'right',
    fontFamily: 'SemplicitaPro-Regular',
  },
  headerTxt: {flexDirection: 'row-reverse', alignItems: 'center'},
});
export default Styles;
