import {StyleSheet} from 'react-native';
import R from '../../resources/R';

const Styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: R.colors.white,
    position: 'relative',
  },
  textContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
  },
  textContainer1: {
    flexDirection: 'row-reverse',
    justifyContent: 'center',
  },
  coloumncontainer: {
    marginTop: 20,
    flex: 1,
    flexDirection: 'row-reverse',
    paddingBottom: 10,
    justifyContent: 'space-between',
    alignContent: 'center',
    marginHorizontal: 20,
  },
  coloumncontainer1: {
    flexDirection: 'row',
    padding: 10,
  },
  coloumncontainer3: {
    flexDirection: 'row-reverse',
    paddingBottom: 10,
  },
  coloumncontainer2: {
    flexDirection: 'column',
    padding: 10,
  },
  flexContainer: {
    flexDirection: 'row-reverse',
    padding: 5,
    paddingRight: 0,
  },
  boxcontainer: {
    borderColor: '#eaeaea',
    borderWidth: 2,
    borderRadius: 5,
    width: '100%',
    padding: 10,
  },

  item: {
    flex: 0.5,
    width: '50%',
    padding: 0,
  },
  item1: {
    flex: 0.5,
    width: '95%',
    padding: 0,
    alignItems: 'flex-end',
  },
  item2: {
    flex: 0.5,
    width: '5%',
    padding: 0,
    alignItems: 'flex-end',
  },
  modalitem1: {
    flex: 0.5,
    width: '60%',
  },
  modalitem2: {
    flex: 0.5,
    width: '40%',
  },

  headingSubTittle: {
    fontSize: 18,
    color: R.colors.gold,
    fontFamily: 'SemplicitaPro-Bold',
  },
  headingBalance: {
    fontSize: 14,
    color: R.colors.blue,
    fontFamily: 'SemplicitaPro-Bold',
    textAlign: 'right',
    marginTop: 2,
  },
  Balance: {
    fontSize: 14,
    color: R.colors.gold,
    fontFamily: 'SemplicitaPro-Bold',
    textAlign: 'right',
    marginTop: 2,
  },
  bodytext: {
    fontSize: 12,
    color: R.colors.lightgray,
    fontFamily: 'SemplicitaPro-Regular',
  },
  bottomView: {
    width: '100%',
    height: 40,
    backgroundColor: '#1c3a69',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    bottom: 0,
    borderTopColor: '#FFEB99',
    borderTopWidth: 4,
  },
  textStyle: {
    color: R.colors.white,
  },
  textStyleB: {
    color: R.colors.white,
    fontFamily: 'SemplicitaPro-Bold',
    fontSize: 11.5,
  },
  textInput: {
    color: R.colors.lightgray,
    fontSize: 12,
    height: 40,
    fontFamily: 'SemplicitaPro-Regular',
    borderRadius: 5,
    backgroundColor: '#F6F9FA',
    borderColor: R.colors.mediumgray,
    borderWidth: 1,
    paddingLeft: 10,
    paddingRight: 10,
    textAlign: 'right',
    justifyContent: 'center',
  },
  blubtn: {
    backgroundColor: R.colors.blue,
    borderRadius: 5,
    padding: 10,
    marginStart: 10,
    marginTop: 5,
    marginBottom: 1,
  },
  buttonClose1: {
    backgroundColor: R.colors.blue,
    fontFamily: 'SemplicitaPro-Bold',
  },
  blubtn1: {
    backgroundColor: R.colors.blue,
    borderRadius: 5,
    padding: 10,
    marginEnd: 10,
    marginTop: 5,
    marginBottom: 1,
    position: 'absolute',
    right: -10,
    top: 5,
  },
  blubtn2: {
    backgroundColor: R.colors.blue,
    borderRadius: 5,
    padding: 7,
    margin: 2,
    width: 35,
    height: 30,
    justifyContent: 'center',
  },
  blubtn3: {
    backgroundColor: R.colors.blue,
    borderRadius: 5,
    padding: 2,
    margin: 2,
    width: 35,
    height: 35,
    justifyContent: 'center',
    paddingLeft: 6,
    paddingTop: Platform.OS == 'android' ? 0 : 8,
    paddingBottom: 0,
  },
  modalView: {
    margin: 10,
    backgroundColor: 'white',
    borderRadius: 0,
    padding: 5,
    display: 'flex',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    marginTop: 70,
  },
  button: {
    borderRadius: 5,
    padding: 10,
    width: 80,
    textAlign: 'center',
    alignItems: 'center',
  },
  buttonOpen: {
    backgroundColor: R.colors.blue,
  },
  buttonClose: {
    backgroundColor: R.colors.darkgray,
    fontFamily: 'SemplicitaPro-Bold',
  },
  buttonCloseb: {
    backgroundColor: R.colors.blue,
    fontFamily: 'SemplicitaPro-Bold',
  },

  modalText: {
    marginBottom: 15,
    textAlign: 'left',
  },
  headingModalContainer: {
    textAlign: 'left',
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    alignSelf: 'flex-start',
    padding: 7,
  },

  headingModalContainers: {
    flexDirection: 'row-reverse',
    marginRight: -5,
  },
  headingModal: {
    fontSize: 16,
    color: R.colors.white,
    fontFamily: 'SemplicitaPro-Bold',
  },
  modalbg: {
    backgroundColor: R.colors.blue,
    padding: 2,
    paddingEnd: 10,
    paddingTop: 5,
    paddingLeft: 10,
    marginBottom: 10,
    width: '103%',
    marginLeft: -5,
    marginTop: -5,
  },
  headingBtn: {
    position: 'absolute',
    right: 10,
    top: 10,
  },
  mandatoryLbl: {
    fontSize: 13,
    color: R.colors.red,
    textAlign: 'right',
    marginBottom: 5,
    alignItems: 'flex-end',
  },
  mandatory: {
    color: R.colors.red,
    fontFamily: 'SemplicitaPro-Bold',
  },
  formLbl: {
    color: R.colors.black,
    fontFamily: 'SemplicitaPro-SemiBold',
    fontSize: 15,
    marginBottom: 5,
    textAlign: 'right',
  },
  formLcen: {
    color: R.colors.blue,
    fontFamily: 'SemplicitaPro-SemiBold',
    fontSize: 15,
    margin: 5,
    textAlign: 'center',
  },
  formLblnb: {
    color: R.colors.black,
    fontFamily: 'SemplicitaPro-Regular',
    fontSize: 15,
    marginBottom: 5,
  },
  formLblb: {
    color: R.colors.blue,
    fontFamily: 'SemplicitaPro-SemiBold',
    fontSize: 15,
    margin: 5,
    textAlign: 'right',
  },
  formmt: {
    marginTop: 12,
  },
  formmb: {
    marginBottom: 7,
  },
  formcontainer: {
    padding: 10,
  },
  formcontainerR: {
    padding: 10,
    textAlign: 'left',
  },
  rangecontainer: {
    paddingLeft: 10,
    paddingRight: 10,
    paddingTop: 10,
    paddingBottom: 10,
    marginTop: 7,
  },
  alignRight: {
    textAlign: 'left',
    alignItems: 'flex-start',
  },
  btnContainer: {
    display: 'flex',
    justifyContent: 'space-between',
    flexDirection: 'row-reverse',
  },

  btnContainer1: {
    display: 'flex',
    justifyContent: 'flex-start',
    flexDirection: 'row-reverse',
    marginLeft: '50%',
    marginTop: 10,
  },
  btnContainer2: {
    display: 'flex',
    justifyContent: 'flex-end',
    flexDirection: 'row-reverse',
  },
  modalBtn: {
    backgroundColor: R.colors.blue,
    padding: 10,
    color: R.colors.white,
    borderRadius: 5,
    fontSize: 13,
    marginTop: 10,
    paddingLeft: 10,
    paddingRight: 10,
    fontFamily: 'SemplicitaPro-Bold',
  },
  header: {
    width: '100%',
    fontFamily: 'SemplicitaPro-SemiBold',
    color: R.colors.black,
    fontSize: 16,
    textAlign: 'right',
    flexDirection: 'row-reverse',
    marginLeft: 10,
    marginRight: 10,
  },
  headers: {
    backgroundColor: '#EAE6E6',
    padding: 10,
    width: '100%',
    elevation: 2,
    borderColor: R.colors.mediumgray,
    borderWidth: 1,
    fontFamily: 'SemplicitaPro-SemiBold',
    color: R.colors.black,
    fontSize: 16,
    justifyContent: 'space-between',
    flexDirection: 'row-reverse',
  },
  headersText: {
    fontFamily: 'SemplicitaPro-SemiBold',
    color: R.colors.black,
    fontSize: 16,
    lineHeight: 25,
    width: '100%',
    marginRight: 10,
    textAlign: 'right',
  },
  headercon: {
    backgroundColor: '#EAE6E6',
    padding: 10,
    width: '100%',
    elevation: 2,
    borderColor: R.colors.mediumgray,
    borderWidth: 1,
    marginTop: 3,
    fontFamily: 'SemplicitaPro-SemiBold',
    color: R.colors.black,
    fontSize: 16,
    flexDirection: 'row-reverse',
  },
  headerText: {
    textAlign: 'right',
    fontSize: 16,
    fontWeight: '500',
    fontFamily: 'SemplicitaPro-Bold',
    color: R.colors.black,
  },
  tableHead: {
    textAlign: 'right',
    fontSize: 16,
    fontWeight: '700',
    fontFamily: 'SemplicitaPro-Bold',
    color: R.colors.black,
  },
  tabletext: {
    padding: 7,
    fontFamily: 'SemplicitaPro-Regular',
    color: R.colors.black,
    textAlign: 'right',
    flexDirection: 'row-reverse',
    flex: 1,
  },

  content: {
    padding: 20,
    width: '100%',
    backgroundColor: '#F6F6F6',
    borderColor: R.colors.mediumgray,
    borderWidth: 1,
  },
  active: {
    backgroundColor: R.colors.blue,
  },
  inactive: {
    backgroundColor: R.colors.gray,
  },
  selectors: {
    marginBottom: 10,
    flexDirection: 'row',
    justifyContent: 'center',
  },
  selector: {
    backgroundColor: '#F5FCFF',
    padding: 10,
  },
  activeSelector: {
    fontWeight: 'bold',
  },
  selectTitle: {
    fontSize: 14,
    fontWeight: '500',
    padding: 10,
    textAlign: 'center',
  },
  lotHeader: {
    backgroundColor: R.colors.blue,
    color: R.colors.white,
    padding: 10,
    textAlign: 'center',
    fontFamily: 'SemplicitaPro-Bold',
    fontSize: 16,
    borderTopLeftRadius: 7,
    borderTopRightRadius: 7,
    marginBottom: -1,
  },
  inputTexts: {
    borderColor: R.colors.mediumgray,
    borderWidth: 1,
    borderRadius: 5,
    backgroundColor: '#F6F9FA',
    marginTop: 10,
    height: 40,
    justifyContent: 'center',
    textAlign: 'right',
  },
  inputTexts1: {
    borderColor: R.colors.mediumgray,
    borderWidth: 1,
    borderRadius: 5,
    backgroundColor: '#F6F9FA',
    marginTop: 1,
    height: 40,
    justifyContent: 'center',
  },
  loadercontainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    flexDirection: 'column',
  },
  checkboxcont: {
    flexDirection: 'row-reverse',
    alignItems: 'flex-end',
    marginLeft: 20,
  },
  chklabel: {
    fontFamily: 'SemplicitaPro-SemiBold',
    color: R.colors.black,
    paddingBottom: 5,
    padding: 5,
  },
  checkbox: {
    width: 20,
    height: 20,
    borderRadius: 4,
    marginBottom: 5,
    marginRight: 5,
  },
  prevlnk: {
    height: 17,
    width: 17,
    resizeMode: 'contain',
    transform: [{scaleX: -1}],
  },
  rowrev: {
    flexDirection: 'row-reverse',
  },
  mrgR: {
    marginLeft: 15,
  },
  Notebg: {
    padding: 10,
    color: '#3c763d',
    backgroundColor: '#dff0d8',
    borderColor: '#d6e9c6',
    marginTop: 10,
  },
  autoSearch: {
    padding: 10,
    borderRightWidth: 1,
    borderLeftWidth: 1,
    borderColor: '#8c8c8c',
    width: '88%',
    alignSelf: 'center',
    zIndex: 999,
    bottom: 77,
    backgroundColor: '#fff',
  },
  expandViewRow: {
    flexDirection: 'row-reverse',
    width: '90%',
    // alignSelf: 'center',
    // alignItems: 'center',
  },
  expandViewKey: {
    width: '50%',
    padding: 10,
  },
  expandViewValue: {
    width: '50%',
    justifyContent: 'flex-end',
    padding: 10,
  },
  addReturn: {
    display: 'flex',
    justifyContent: 'space-between',
    flexDirection: 'row',
  },
  expandViewValue_1: {
    width: '50%',
    justifyContent: 'flex-end',
    padding: 10,
    flexDirection: 'row-reverse',
  },
  smartSearchText: {
    fontSize: 14,
    color: R.colors.black,
    fontFamily: 'SemplicitaPro-Regular',
    padding: 2,
  },
  headerTxtList: {flexDirection: 'row-reverse', alignItems: 'center'},
  headerTxt: {flexDirection: 'row-reverse', alignItems: 'center'},
  pressedMarkerStyle: {
    height: 35,
    width: 100,
    borderRadius: 0,
    justifyContent: 'center',
    backgroundColor: R.colors.white,
    shadowColor: '#000000',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowRadius: 1,
    shadowOpacity: 0.1,
  },
  markerStyle: {
    height: 26,
    width: 47,
    borderRadius: 0,
    justifyContent: 'center',
    backgroundColor: R.colors.white,
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowRadius: 1,
    shadowOpacity: 0.1,
  },
});
export default Styles;
