import {StyleSheet, Dimensions} from 'react-native';
import R from '../../resources/R';

const {width} = Dimensions.get('window');

const Styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: R.colors.white,
    paddingTop: 40,
  },
  textContainer: {
    marginTop: 20,
    marginHorizontal: 35,
  },
  coloumncontainer: {
    alignItems: 'center',
    flexDirection: 'column',
    justifyContent: 'center',
    paddingBottom: 10,
  },
  textColoumnContainers: {
    marginBottom: 20,
  },
  headingTittle: {
    fontSize: 30,
    color: R.colors.black,
        fontFamily: 'SemplicitaPro-SemiBold',

  },
  bodytext: {
    fontSize: 12,
    color: R.colors.lightgray,
    fontFamily: 'SemplicitaPro-Regular',
  },

  textColoumnContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    width: width,
    marginTop: 25,
    marginBottom: 20,
    alignSelf: 'center',
  },
  btnImage: {
    resizeMode: 'contain',
    height: '100%',
    width: '100%',
    tintColor: '#D8D8D8',
  },
  textFieldContainer: {},
  textInput: {
    color: R.colors.lightgray,
    fontSize: 12,
    height: 40,
    fontFamily: 'SemplicitaPro-Regular',
    backgroundColor: '#E8F0FE',
  },
  inputLayout: {
    marginTop: 5,
    color: R.colors.lightgray,
    fontFamily: 'SemplicitaPro-Regular',
    borderBottomColor: R.colors.orange,
    borderBottomWidth: 1.5,
  },
  passwordinputLayout: {
    marginTop: 5,
    color: R.colors.lightgray,
    fontFamily: 'SemplicitaPro-Regular',
  },
  blueText: {
    color: R.colors.blue,
    fontFamily: 'SemplicitaPro-Bold',
    textDecorationLine: 'underline',
    lineHeight: 27,
    marginVertical: -6,
  },
  grayText: {
    fontSize: 14,
    color: R.colors.grayText,
    fontFamily: 'SemplicitaPro-Bold',
    textAlign: 'center',
    lineHeight: 20,
  },
  linkText: {
    fontSize: 12,
    color: R.colors.white,
    textDecorationLine: 'underline',
    fontFamily: 'SemplicitaPro-Regular',
  },
  button: {
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    paddingTop: 5,
    paddingBottom: 10,
    borderRadius: 5,
    height: 40,
    lineHeight: 25,
    width: 120,
    marginTop: 25,
    marginBottom: 15,
    backgroundColor: R.colors.blue,
    fontFamily: 'SemplicitaPro-Bold',
  },
  SectionStyle: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    height: 45,
    borderColor: R.colors.mediumgray,
    borderWidth: 1,
    borderRadius: 5,
    backgroundColor: '#F6F9FA',
    textAlign: 'right',
  },
  FucusedSectionStyle: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    height: 40,
    color: R.colors.black,
    borderColor: R.colors.mediumgray,
    borderWidth: 1,
    backgroundColor: '#F6F9FA',
    textAlign: 'right',
  },
  titleText: {
    color: R.colors.black,
    fontSize: 12,
    fontFamily: 'SemplicitaPro-SemiBold',
    marginTop: 30,
    marginBottom: 10,
  },
  textRowContainer: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    flex: 1,
    marginTop: 5,
    alignContent: 'flex-start',
  },
  inputText: {
    flex: 1,
    height: 40,
    color: R.colors.black,
    fontSize: 12,
    fontFamily: 'SemplicitaPro-Regular',
    paddingLeft: 10,
    paddingRight: 10,
    textAlign: 'right',
    flexDirection: 'row-reverse',
  },
  reqText: {
    color: R.colors.red,
  },
  bottomView: {
    width: '100%',
    height: 40,
    backgroundColor: R.colors.blue,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    bottom: 0,
    borderTopColor: '#FFEB99',
    borderTopWidth: 4,
  },
  textStyle: {
    color: R.colors.white,
  },
  textStyleB: {
    color: R.colors.white,
    fontFamily: 'SemplicitaPro-Bold',
  },
  btncontainer: {
    display: 'flex',
    flexDirection: 'row-reverse',
    paddingTop: 10,
    paddingLeft: 0,
    alignItems: 'center',
    justifyContent: 'center',
  },
  subBtn: {
    backgroundColor: R.colors.blue,
    fontFamily: 'SemplicitaPro-Bold',
    borderRadius: 5,
    padding: 10,
    marginStart: 10,
    marginTop: 5,
    marginBottom: 1,
    alignItems: 'center',
    width: 150,
  },
  subBtnA: {
    backgroundColor: R.colors.darkgray,
    fontFamily: 'SemplicitaPro-Bold',
    borderRadius: 5,
    padding: 10,
    marginStart: 10,
    marginTop: 5,
    marginBottom: 1,
    alignItems: 'center',
    width: 150,
  },
  canBtn: {
    backgroundColor: R.colors.blue,
    fontFamily: 'SemplicitaPro-Bold',
    borderRadius: 5,
    padding: 10,
    marginTop: 5,
    marginBottom: 1,
    alignItems: 'center',
    width: 150,
  },
  canBtnA: {
    backgroundColor: R.colors.darkgray,
    fontFamily: 'SemplicitaPro-Bold',
    borderRadius: 5,
    padding: 10,
    marginTop: 5,
    marginBottom: 1,
    alignItems: 'center',
    width: 150,
  },
  mrTop30: {
    marginTop: 30,
  },
  mrTop50: {
    marginTop: 50,
  },
  loadercontainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    flexDirection: 'column',
  },
});
export default Styles;
