import {StyleSheet} from 'react-native';
import R from '../../resources/R';

const Styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: R.colors.white,
  },
  textContainer: {
    marginTop: 20,
    marginHorizontal: 20,
  },
  coloumncontainer: {
    flexDirection: 'row-reverse',
    paddingBottom: 10,
  },
  coloumncontainers: {
    flex: 1,
    flexDirection: 'column',
    padding: 20,
    marginRight: 5,
  },
  flexitemleft: {
    flex: '60%',
  },
  flexitemright: {
    flex: '40%',
  },
  item: {
    flex: 0.5,
    width: '50%',
    padding: 0,
  },
  headingSubTittle: {
    fontSize: 18,
    color: R.colors.gold,
    fontFamily: 'SemplicitaPro-Bold',
  },
  mandatoryLbl: {
    fontSize: 13,
    color: R.colors.red,
    textAlign: 'right',
    marginBottom: 5,
    alignItems: 'flex-end',
  },
  mandatory: {
    color: R.colors.red,
    fontSize: 13,
  },
  bodytext: {
    fontSize: 12,
    color: R.colors.lightgray,
    fontFamily: 'SemplicitaPro-Regular',
  },
  bottomView: {
    width: '100%',
    height: 40,
    backgroundColor: R.colors.blue,
    justifyContent: 'center',
    alignItems: 'center',
    bottom: 0,
    borderTopColor: '#FFEB99',
    borderTopWidth: 4,
  },
  textStyle: {
    color: R.colors.white,
  },
  textStyleB: {
    color: R.colors.white,
    fontFamily: 'SemplicitaPro-Bold',
    fontSize: 16,
  },
  textStylelarge: {
    color: R.colors.black,
    fontSize: 34,
    fontFamily: 'SemplicitaPro-Bold',
    marginRight: 20,
    paddingTop: 5,
  },
  valuecont: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  blueBkg: {
    backgroundColor: R.colors.blue,
    padding: 10,
    width: '104%',
    marginTop: 1,
    paddingRight: 20,
    borderBottomStartRadius: 15,
    elevation: 5,
    marginRight: -15,
    paddingBottom: 15,
    textAlign: 'right',
  },
  blueBkgInverted: {
    backgroundColor: R.colors.blue,
    padding: 12,
    width: 10,
    right: 14,
    top: Platform.OS == 'android' ? 64 : 60,
    position: 'absolute',
    transform: [{rotate: '30deg'}],
  },
  subTitle: {
    color: R.colors.white,
    fontSize: 18,
    fontFamily: 'SemplicitaPro-Bold',
    textAlign: 'right',
  },
  portlet: {
    borderColor: '#e2e2e2',
    borderWidth: 1,
    width: '100%',
    padding: 15,
    borderTopWidth: 0,
    marginTop: -5,
    elevation: 1,
    marginBottom: 10,
    backgroundColor: R.colors.white,
    borderRadius: 7,
  },
  formLbl: {
    color: R.colors.black,
    fontFamily: 'SemplicitaPro-Regular',
    fontSize: 16,
    marginBottom: 5,
  },
  formmt: {
    marginTop: 15,
  },

  SectionStyle: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 45,
    borderColor: R.colors.mediumgray,
    borderWidth: 1,
    borderRadius: 5,
    backgroundColor: '#F6F9FA',
  },
  FucusedSectionStyle: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 40,
    color: R.colors.black,
    borderColor: R.colors.mediumgray,
    borderWidth: 1,
    backgroundColor: '#F6F9FA',
  },
  textInput: {
    color: R.colors.lightgray,
    fontSize: 12,
    height: 40,
    fontFamily: 'SemplicitaPro-Regular',
    borderRadius: 5,
    backgroundColor: '#F6F9FA',
    borderColor: R.colors.mediumgray,
    borderWidth: 1,
  },

  inputLayout: {
    marginTop: 5,
    color: R.colors.lightgray,
    fontFamily: 'SemplicitaPro-Regular',
    borderBottomColor: R.colors.orange,
    borderBottomWidth: 1.5,
  },
  marginBot: {
    marginBottom: 30,
  },
  subBtn: {
    backgroundColor: R.colors.blue,
    fontFamily: 'SemplicitaPro-Bold',
    borderRadius: 5,
    padding: 0,
    marginEnd: 10,
    height: 42,
    width: 80,
    paddingTop: 7,
    alignItems: 'center',
    marginTop: 10,
  },

  headercontainer: {
    padding: 0,
    margin: 0,
  },
  headerimage: {
    width: 552,
    height: 70,
    marginLeft: -10,
  },
  toggle: {
    position: 'absolute',
    right: 5,
    top: 15,
  },
  headerlogo: {
    position: 'absolute',
    left: 35,
    top: -30,
    zIndex: 2,
  },

  animatedBox: {
    flex: 1,
    backgroundColor: '#fff',
    marginRight: -10,
    marginLeft: 10,
    elevation: 5,
  },
  body: {
    flex: 1,
  },
  draweruserbg: {
    backgroundColor: R.colors.darkblue,
    padding: 20,
  },
  logoimage: {
    aspectRatio: 1,
    flex: 1,
    maxWidth: 80,
    resizeMode: 'contain',
  },
  draweruser: {
    fontSize: 18,
    color: R.colors.white,
    marginTop: 20,
    fontFamily: 'SemplicitaPro-Bold',
  },
  drawerclose: {
    fontSize: 18,
    color: R.colors.white,
    marginTop: 20,
    fontFamily: 'SemplicitaPro-Bold',
    marginRight: 25,
    paddingRight: 25,
  },
  drawermenu: {
    color: R.colors.blue,
    padding: 20,
    borderColor: R.colors.gray,
    borderBottomWidth: 1,
  },
  drawermenusub: {
    marginLeft: 50,
    margin: 20,
  },
  menuimg: {
    height: 26,
    width: 26,
    resizeMode: 'contain',
    margin: 20,
  },
  formcont: {
    display: 'flex',
    flexDirection: 'row-reverse',
  },
  formLblr: {
    color: R.colors.blue,
    fontFamily: 'SemplicitaPro-Medium',
    fontSize: 16,
    marginBottom: 5,
    fontWeight: '600',
    width: '50%',
    textAlign: 'right',
  },

  formLbll: {
    color: R.colors.black,
    fontFamily: 'SemplicitaPro-Regular',
    fontSize: 16,
    marginBottom: 5,
    // fontWeight:'600',
    width: '50%',
    textAlign: 'right',
  },
  blubtn: {
    backgroundColor: R.colors.blue,
    borderRadius: 5,
    padding: 10,
    paddingLeft: 15,
    marginTop: 5,
    marginBottom: 1,
    minWidth: 60,
    textAlign: 'center',
    alignItems: 'flex-end',
    alignSelf: 'flex-end',
    marginRight: 20,
  },
  Convimgcon: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  Convimg: {
    width: 100,
    height: 100,
    borderWidth: 1,
    borderColor: R.colors.mediumgray,
    resizeMode: 'contain',
    padding: 5,
    borderRadius: 15,
  },
  loadercontainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    flexDirection: 'column',
  },
  prevlnk: {
    height: 17,
    width: 17,
    resizeMode: 'contain',
    transform: [{scaleX: -1}],
  },
  headerTxt: {flexDirection: 'row-reverse', alignItems: 'center'},
});
export default Styles;
